export interface GlossaryTerm {
  term: string;
  area: string;
  definition: string;
  relatedArt?: string;
}

export const GLOSSARY: GlossaryTerm[] = [
  { term: "Acórdão", area: "Processual", definition: "Decisão proferida por órgão colegiado de tribunal." },
  { term: "Agravo de Instrumento", area: "Processual", definition: "Recurso cabível contra decisão interlocutória.", relatedArt: "art. 1.015 CPC" },
  { term: "Alegações finais", area: "Penal", definition: "Manifestação das partes após instrução criminal, fixando teses para a sentença.", relatedArt: "art. 403 CPP" },
  { term: "Apelação", area: "Processual", definition: "Recurso contra sentença, com prazo de 15 dias úteis.", relatedArt: "art. 1.009 CPC" },
  { term: "Astreintes", area: "Processual", definition: "Multa coercitiva imposta para forçar cumprimento de obrigação de fazer ou não fazer.", relatedArt: "art. 537 CPC" },
  { term: "Causa de pedir", area: "Processual", definition: "Conjunto dos fatos e fundamentos jurídicos que justificam o pedido." },
  { term: "Coisa julgada", area: "Processual", definition: "Imutabilidade da decisão de mérito após esgotados os recursos.", relatedArt: "art. 502 CPC" },
  { term: "Contestação", area: "Processual", definition: "Resposta do réu, com preliminares e impugnação ao mérito.", relatedArt: "art. 335 CPC" },
  { term: "Cumprimento de sentença", area: "Processual", definition: "Fase executiva para cumprir o título judicial.", relatedArt: "art. 523 CPC" },
  { term: "Custas processuais", area: "Processual", definition: "Despesas para movimentar o processo (taxa judiciária, oficial de justiça, etc.)." },
  { term: "Decisão interlocutória", area: "Processual", definition: "Decisão que resolve questão incidente, sem por fim ao processo." },
  { term: "Defesa preliminar", area: "Penal", definition: "Resposta antes do recebimento da denúncia (alguns ritos)." },
  { term: "Despejo", area: "Civil", definition: "Ação para retomada de imóvel locado.", relatedArt: "Lei 8.245/91" },
  { term: "Dano moral", area: "Civil", definition: "Lesão à dignidade ou direito da personalidade, indenizável.", relatedArt: "art. 5º, V e X, CF" },
  { term: "Dolo", area: "Penal", definition: "Vontade consciente de praticar o crime ou assumir o risco do resultado.", relatedArt: "art. 18, I, CP" },
  { term: "Embargos de declaração", area: "Processual", definition: "Recurso para sanar omissão, contradição, obscuridade ou erro material.", relatedArt: "art. 1.022 CPC" },
  { term: "Estado de necessidade", area: "Penal", definition: "Excludente de ilicitude para conduta praticada para salvar de perigo atual.", relatedArt: "art. 24 CP" },
  { term: "Execução fiscal", area: "Tributário", definition: "Ação de cobrança de dívida ativa da Fazenda Pública.", relatedArt: "Lei 6.830/80" },
  { term: "Foro de eleição", area: "Civil", definition: "Cláusula que define o foro competente em contratos." },
  { term: "Fumus boni iuris", area: "Processual", definition: "Aparência do bom direito; requisito para tutela de urgência.", relatedArt: "art. 300 CPC" },
  { term: "Guarda compartilhada", area: "Família", definition: "Modelo em que ambos os pais exercem o poder familiar conjuntamente.", relatedArt: "art. 1.584 CC" },
  { term: "Habeas Corpus", area: "Penal", definition: "Ação constitucional contra constrangimento ilegal à liberdade de locomoção.", relatedArt: "art. 5º, LXVIII, CF" },
  { term: "Honorários sucumbenciais", area: "Processual", definition: "Verba devida ao advogado da parte vencedora pelo perdedor.", relatedArt: "art. 85 CPC" },
  { term: "Impenhorabilidade", area: "Processual", definition: "Bens que não podem ser penhorados para pagamento de dívida.", relatedArt: "art. 833 CPC" },
  { term: "Inépcia da inicial", area: "Processual", definition: "Vício na petição inicial que impede o regular processamento.", relatedArt: "art. 330 CPC" },
  { term: "Inversão do ônus da prova", area: "Consumidor", definition: "Transferência do dever de provar do consumidor ao fornecedor.", relatedArt: "art. 6º, VIII, CDC" },
  { term: "Justa causa (processual)", area: "Processual", definition: "Motivo legítimo para superar prazo perdido.", relatedArt: "art. 223 §1º CPC" },
  { term: "Legitimidade ad causam", area: "Processual", definition: "Pertinência subjetiva entre a parte e o direito discutido." },
  { term: "Litisconsórcio", area: "Processual", definition: "Pluralidade de partes no mesmo polo da relação processual.", relatedArt: "art. 113 CPC" },
  { term: "Mandado de Segurança", area: "Constitucional", definition: "Ação contra ato ilegal de autoridade que viole direito líquido e certo.", relatedArt: "Lei 12.016/09" },
  { term: "Manifesto", area: "Processual", definition: "Petição em que a parte se posiciona sobre ato anterior do processo." },
  { term: "Mora", area: "Civil", definition: "Atraso no cumprimento da obrigação.", relatedArt: "art. 394 CC" },
  { term: "Multa diária (astreintes)", area: "Processual", definition: "Imposta para forçar cumprimento de obrigação de fazer ou não fazer.", relatedArt: "art. 537 CPC" },
  { term: "Negativação", area: "Consumidor", definition: "Inscrição do nome em cadastro de proteção ao crédito (SPC, Serasa)." },
  { term: "Nexo causal", area: "Civil", definition: "Vínculo de causa e efeito entre conduta e dano.", relatedArt: "art. 186 CC" },
  { term: "Ônus da prova", area: "Processual", definition: "Encargo de demonstrar a veracidade de um fato.", relatedArt: "art. 373 CPC" },
  { term: "Pedido", area: "Processual", definition: "Providência específica que se busca do Judiciário." },
  { term: "Periculum in mora", area: "Processual", definition: "Perigo de dano se a tutela demorar; requisito para tutela de urgência." },
  { term: "Peticionamento eletrônico", area: "Processual", definition: "Protocolo de peças via sistemas como PJe, e-SAJ, eproc." },
  { term: "Petição inicial", area: "Processual", definition: "Peça que inaugura o processo, com qualificação, fatos, fundamentos e pedidos.", relatedArt: "art. 319 CPC" },
  { term: "Poder familiar", area: "Família", definition: "Conjunto de direitos e deveres dos pais sobre os filhos menores.", relatedArt: "art. 1.630 CC" },
  { term: "Prazo dilatório", area: "Processual", definition: "Prazo que pode ser estendido por convenção das partes ou pelo juiz." },
  { term: "Prazo peremptório", area: "Processual", definition: "Prazo que não admite prorrogação por convenção." },
  { term: "Prescrição", area: "Civil", definition: "Perda da pretensão pelo decurso do tempo.", relatedArt: "art. 189 CC" },
  { term: "Preliminar", area: "Processual", definition: "Matéria processual examinada antes do mérito (ex.: prescrição, ilegitimidade)." },
  { term: "Procuração ad judicia", area: "Extrajudicial", definition: "Instrumento de mandato para atuação processual." },
  { term: "Recurso especial", area: "Processual", definition: "Recurso ao STJ contra violação à lei federal.", relatedArt: "art. 105, III, CF" },
  { term: "Recurso extraordinário", area: "Processual", definition: "Recurso ao STF contra violação à Constituição.", relatedArt: "art. 102, III, CF" },
  { term: "Réplica", area: "Processual", definition: "Manifestação do autor sobre a contestação.", relatedArt: "art. 350 CPC" },
  { term: "Rescisão indireta", area: "Trabalho", definition: "Resolução do contrato por falta grave do empregador.", relatedArt: "art. 483 CLT" },
  { term: "Saneamento e organização", area: "Processual", definition: "Decisão que fixa pontos controvertidos e provas a produzir.", relatedArt: "art. 357 CPC" },
  { term: "Sentença", area: "Processual", definition: "Ato do juiz que põe fim à fase de conhecimento.", relatedArt: "art. 203 §1º CPC" },
  { term: "Súmula vinculante", area: "Constitucional", definition: "Súmula do STF de observância obrigatória.", relatedArt: "art. 103-A CF" },
  { term: "Tutela de urgência", area: "Processual", definition: "Provimento liminar com probabilidade do direito + perigo de dano.", relatedArt: "art. 300 CPC" },
  { term: "Tutela da evidência", area: "Processual", definition: "Tutela concedida com base em probabilidade qualificada, sem urgência.", relatedArt: "art. 311 CPC" },
  { term: "Trânsito em julgado", area: "Processual", definition: "Momento em que não cabe mais recurso da decisão." },
  { term: "Vícios redibitórios", area: "Civil", definition: "Defeitos ocultos no produto que o tornam impróprio ao uso.", relatedArt: "art. 441 CC" },
  { term: "Vista dos autos", area: "Processual", definition: "Acesso da parte aos autos do processo." },
];

export const GLOSSARY_AREAS = Array.from(new Set(GLOSSARY.map((g) => g.area))).sort();
